environment:
  matrix:
    - node_js: 7
    - node_js: 8
    - node_js: 9
    - node_js: 10
    - node_js: 11

before_test:
  - npm i

test_script:
  - node --version
  - npm test

###

build: off

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> yarn.lock
  - example/node_modules -> yarn.lock

clone_depth: 1

install:
  - ps: Install-Product node $env:node_js $env:platform

matrix:
  fast_finish: true

platform:
  - x86
  - x64

shallow_clone: true

version: '#{build}'
